version: '3.8'

secrets:
  cloudflare_api_token:
    file: ./cloudflare_api_token.env

services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CADDY_VERSION: 2 # Or your desired Caddy version like 2.8.4
    container_name: caddy
    restart: no
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # For HTTP/3
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile --envfile /run/secrets/cloudflare_api_token
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      # below two lines are different from caddy-hetzner/docker-compose.yaml
      - ./Caddyfile.internal:/etc/caddy/Caddyfile
      - /var/run/tailscaled.socket:/var/run/tailscale/tailscaled.sock:ro
    secrets:
      - cloudflare_api_token
    networks:
      - proxy_network

volumes:
  caddy_data:
  caddy_config:

networks:
  proxy_network:
    name: proxy_network
    driver: bridge
