secrets:
  cloudflare_api_token:
    file: ./cloudflare_api_token.env

services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caddy-internal
    restart: no
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      # below two lines are different from caddy-hetzner/docker-compose.yaml
      - ./Caddyfile.internal:/etc/caddy/Caddyfile
      - /var/run/tailscaled.socket:/var/run/tailscale/tailscaled.sock:ro
    networks:
      - proxy_network
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile --envfile /run/secrets/cloudflare_api_token
    secrets:
      - cloudflare_api_token

volumes:
  caddy_data:
  caddy_config:

networks:
  proxy_network:
    name: proxy_network
    driver: bridge
