[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py","pyi","py3","pyw","ptl",".pythonstartup",".pythonrc","SConstruct"]
shebangs = ["python"]
roots = ["setup.py", "setup.cfg", "pyproject.toml"]
comment-token = "#"
language-servers = [ "pyright-lsp", "ruff"]
indent = { tab-width = 4, unit = "    " }
# will get "Async jobs timed out" errors if this empty config is not added

[language-server.pyright-lsp]
command = "pyright-ls-helix"
config = { }

[language-server.ruff]
command = "ruff-lsp"
config = { settings = { run = "onSave" } }

[[language]]
# modified from source github repo to add jsonl
name = "json"
scope = "source.json"
injection-regex = "json"
file-types = [
  "json",
  "jsonl",
  "jsonc",
  "arb",
  "ipynb",
  "geojson",
  "gltf",
  "webmanifest",
  "flake.lock",
  ".babelrc",
  ".bowerrc",
  ".jscrc",
  "js.map",
  "ts.map",
  "css.map",
  ".jslintrc",
  "jsonld",
  ".vuerc",
  "composer.lock",
  ".watchmanconfig",
  "avsc",
  ".prettierrc"
]
language-servers = [ "vscode-json-language-server" ]
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "markdown"
language-servers = ["markdown"]
soft-wrap.enable = true

[language-server.markdown]
command = "/Users/cam45819/.cargo/bin/mdpls" 

[[language]]
name = "sql"
language-servers = [ "sql-language-server" ]

[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[[language]]
name = "dockerfile"
scope = "source.dockerfile"
injection-regex = "docker|dockerfile"
roots = ["Dockerfile", "Containerfile"]
file-types = ["Dockerfile", "dockerfile", "Containerfile", "containerfile", "Dockerfile.env", "Dockerfile.code"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
language-servers = [ "docker-langserver" ]
