secrets:
  cloudflare_api_token:
    file: ./cloudflare_api_token.env

services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    image: caddy-cloudflare:latest
    container_name: caddy-hetzner
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      # below line is different from caddy-internal/docker-compose.yaml
      - ./Caddyfile.hetzner:/etc/caddy/Caddyfile:ro
    networks:
      - proxy_network
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile --envfile /run/secrets/cloudflare_api_token
    secrets:
      - cloudflare_api_token

volumes:
  caddy_data:
  caddy_config:

networks:
  proxy_network:
    external: true
