services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    image: caddy-cloudflare:latest
    container_name: caddy-hetzner
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./cloudflare_api_token.env
    networks:
      - proxy_network
    volumes:
      - ./Caddyfile.hetzner:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts:
      - "acme-v02.api.letsencrypt.org:172.65.32.248"
      - "acme-staging-v02.api.letsencrypt.org:172.65.46.172"
      - "host.docker.internal:host-gateway"

volumes:
  caddy_data:
  caddy_config:

networks:
  proxy_network:
    external: true


