services:
  firefly:
    image: fireflyiii/core:latest
    container_name: firefly
    restart: no
    volumes:
      - /Users/callum/.local/state/firefly-iii:/var/www/html/storage/upload
    env_file: .env
    networks:
      # - firefly_iii
      - proxy_network
    ports:
      - 9988:8080
    # depends_on:
    #   - db
  # db:
  #   image: mariadb:lts
  #   hostname: db
  #   container_name: firefly_iii_db
  #   restart: always
  #   env_file: .db.env
  #   networks:
  #     - firefly_iii
  #   volumes:
  #     - firefly_iii_db:/var/lib/mysql
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace PLEASE_REPLACE_WITH_32_CHAR_CODE below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: always
    container_name: firefly_iii_cron
    env_file: .env
    command: sh -c "
      apk add tzdata
      && ln -s /usr/share/zoneinfo/${TZ} /etc/localtime
      | echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/${STATIC_CRON_TOKEN};echo\" 
      | crontab - 
      && crond -f -L /dev/stdout"
    networks:
      # - firefly_iii
      - proxy_network

# volumes:
#    firefly_iii_upload:
#      driver_opts:
#        type: bind
#        device: /Users/callum/.local/state/firefly-iii
#    firefly_iii_db:

networks:
  proxy_network:
    external: true
  # firefly_iii:
  #   driver: bridge